# Generated by Django 4.1.7 on 2023-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="commission_amt",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_contact",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="farmer_contact",
            field=models.PositiveBigIntegerField(),
        ),
    ]
