# Generated by Django 4.1.7 on 2023-04-23 03:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_alter_employee_admin_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="commission_amt",
        ),
    ]
