# Generated by Django 4.1.7 on 2023-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_alter_payment_options_remove_milk_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="milk",
            name="fat_rate",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
