# Generated by Django 4.1.7 on 2023-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_milk_fat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milk',
            name='milk_type',
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
