# Generated by Django 4.1.3 on 2023-05-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_milk_farmer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatrate',
            name='type_of_milk',
        ),
        migrations.RemoveField(
            model_name='milk',
            name='fat_rate',
        ),
    ]
