# Generated by Django 4.1.7 on 2023-05-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_milk_fat_alter_milk_qty_alter_milk_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milk',
            name='rate',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
