# Generated by Django 4.1.7 on 2023-05-29 01:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0032_employee_user_alter_employee_admin_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
    ]
