# Generated by Django 4.1.7 on 2023-05-29 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0033_remove_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
