# Generated by Django 4.1.7 on 2023-05-31 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0035_alter_commission_admin_id_alter_commission_emp_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="admin_id",
        ),
        migrations.RemoveField(
            model_name="farmer",
            name="admin_id",
        ),
    ]
