# Generated by Django 4.1.7 on 2023-05-31 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("dashboard", "0036_remove_employee_admin_id_remove_farmer_admin_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission",
                to="user.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_emp",
                to="user.employee",
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="farmer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_farmer",
                to="user.farmer",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="admin_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_admin",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="user.employee",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="farmer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_farmer",
                to="user.farmer",
            ),
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
        migrations.DeleteModel(
            name="Farmer",
        ),
    ]
