# Generated by Django 4.1.7 on 2023-05-31 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_farmerprofile_is_active"),
        ("dashboard", "0037_alter_commission_emp_id_alter_milk_emp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="milk",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_emp",
                to="user.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="milk",
            name="farmer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milk_farmer",
                to="user.farmerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="emp_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="user.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="farmer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_farmer",
                to="user.farmerprofile",
            ),
        ),
    ]
