# Generated by Django 4.1.7 on 2023-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0038_alter_milk_emp_id_alter_milk_farmer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
