# Generated by Django 4.1.7 on 2023-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0039_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
